<a href="https://colab.research.google.com/github/sriyadd/International-Debt-Analysis-World-Bank/blob/main/IDS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

!pip install chardet

Requirement already satisfied: chardet in /usr/local/lib/python3.11/dist-packages (5.2.0)

In [3]:
import pandas as pd
# Attempt to read the CSV with different encodings, starting with common ones like ISO-8859-1 and then try utf-16
try:
    df_orig = pd.read_csv('/content/IDS_ALLCountries_Data.csv', encoding='ISO-8859-1')
    print("Successfully read with ISO-8859-1 encoding")
except UnicodeDecodeError:
    try:
        df_orig = pd.read_csv('/content/IDS_ALLCountries_Data.csv', encoding='latin1')
        print("Successfully read with latin1 encoding")
    except UnicodeDecodeError:
       try:
            df_orig = pd.read_csv('/content/IDS_ALLCountries_Data.csv', encoding='utf-16')
            print("Successfully read with utf-16 encoding")
       except UnicodeDecodeError:
            # If none of the above encodings work, try auto-detect using chardet
            import chardet
            with open('/content/IDS_ALLCountries_Data.csv', 'rb') as f:
                result = chardet.detect(f.read())  # Detect encoding of the file
            encoding = result['encoding']
            print(f"Detected encoding: {encoding}")
            df_orig = pd.read_csv('/content/IDS_ALLCountries_Data.csv', encoding=encoding)
            print("Successfully read with auto-detected encoding")

# Display the first few rows of the dataframe
print(df_orig.head(30))

Successfully read with ISO-8859-1 encoding
   Country Name Country Code Counterpart-Area Name Counterpart-Area Code  \
0   Afghanistan          AFG                 World                   WLD
1   Afghanistan          AFG                 World                   WLD
2   Afghanistan          AFG                 World                   WLD
3   Afghanistan          AFG                 World                   WLD
4   Afghanistan          AFG                 World                   WLD
5   Afghanistan          AFG                 World                   WLD
6   Afghanistan          AFG                 World                   WLD
7   Afghanistan          AFG                 World                   WLD
8   Afghanistan          AFG                 World                   WLD
9   Afghanistan          AFG                 World                   WLD
10  Afghanistan          AFG                 World                   WLD
11  Afghanistan          AFG                 World                   WLD
12  Afghanistan          AFG                 World                   WLD
13  Afghanistan          AFG                 World                   WLD
14  Afghanistan          AFG                 World                   WLD
15  Afghanistan          AFG                 World                   WLD
16  Afghanistan          AFG                 World                   WLD
17  Afghanistan          AFG                 World                   WLD
18  Afghanistan          AFG                 World                   WLD
19  Afghanistan          AFG                 World                   WLD
20  Afghanistan          AFG                 World                   WLD
21  Afghanistan          AFG                 World                   WLD
22  Afghanistan          AFG                 World                   WLD
23  Afghanistan          AFG                 World                   WLD
24  Afghanistan          AFG                 World                   WLD
25  Afghanistan          AFG                 World                   WLD
26  Afghanistan          AFG                 World                   WLD
27  Afghanistan          AFG                 World                   WLD
28  Afghanistan          AFG                 World                   WLD
29  Afghanistan          AFG                 World                   WLD

                                          Series Name        Series Code  \
0   Average grace period on new external debt comm...        DT.GPA.DPPG
1   Average grace period on new external debt comm...        DT.GPA.OFFT
2   Average grace period on new external debt comm...        DT.GPA.PRVT
3   Average grant element on new external debt com...        DT.GRE.DPPG
4   Average grant element on new external debt com...        DT.GRE.OFFT
5   Average grant element on new external debt com...        DT.GRE.PRVT
6   Average interest on new external debt commitme...        DT.INR.DPPG
7   Average interest on new external debt commitme...        DT.INR.OFFT
8   Average interest on new external debt commitme...        DT.INR.PRVT
9   Average maturity on new external debt commitme...        DT.MAT.DPPG
10  Average maturity on new external debt commitme...        DT.MAT.OFFT
11  Average maturity on new external debt commitme...        DT.MAT.PRVT
12                   CB, bilateral (AMT, current US$)  DT.AMT.BLAT.CB.CD
13                   CB, bilateral (DIS, current US$)  DT.DIS.BLAT.CB.CD
14                   CB, bilateral (DOD, current US$)  DT.DOD.BLAT.CB.CD
15                   CB, bilateral (INT, current US$)  DT.INT.BLAT.CB.CD
16                   CB, bilateral (NFL, current US$)  DT.NFL.BLAT.CB.CD
17                   CB, bilateral (NTR, current US$)  DT.NTR.BLAT.CB.CD
18                   CB, bilateral (TDS, current US$)  DT.TDS.BLAT.CB.CD
19      CB, bilateral concessional (AMT, current US$)  DT.AMT.BLTC.CB.CD
20      CB, bilateral concessional (DIS, current US$)  DT.DIS.BLTC.CB.CD
21      CB, bilateral concessional (DOD, current US$)  DT.DOD.BLTC.CB.CD
22      CB, bilateral concessional (INT, current US$)  DT.INT.BLTC.CB.CD
23      CB, bilateral concessional (NFL, current US$)  DT.NFL.BLTC.CB.CD
24      CB, bilateral concessional (NTR, current US$)  DT.NTR.BLTC.CB.CD
25      CB, bilateral concessional (TDS, current US$)  DT.TDS.BLTC.CB.CD
26                       CB, bonds (AMT, current US$)  DT.AMT.PBND.CB.CD
27                       CB, bonds (DIS, current US$)  DT.DIS.PBND.CB.CD
28                       CB, bonds (DOD, current US$)  DT.DOD.PBND.CB.CD
29                       CB, bonds (INT, current US$)  DT.INT.PBND.CB.CD

    1970  1971  1972  1973  ...  2022  2023  2024  2025  2026  2027  2028  \
0    NaN   NaN   NaN   NaN  ...   0.0   0.0   NaN   NaN   NaN   NaN   NaN
1    NaN   NaN   NaN   NaN  ...   0.0   0.0   NaN   NaN   NaN   NaN   NaN
2    NaN   NaN   NaN   NaN  ...   0.0   0.0   NaN   NaN   NaN   NaN   NaN
3    NaN   NaN   NaN   NaN  ...   0.0   0.0   NaN   NaN   NaN   NaN   NaN
4    NaN   NaN   NaN   NaN  ...   0.0   0.0   NaN   NaN   NaN   NaN   NaN
5    NaN   NaN   NaN   NaN  ...   0.0   0.0   NaN   NaN   NaN   NaN   NaN
6    NaN   NaN   NaN   NaN  ...   0.0   0.0   NaN   NaN   NaN   NaN   NaN
7    NaN   NaN   NaN   NaN  ...   0.0   0.0   NaN   NaN   NaN   NaN   NaN
8    NaN   NaN   NaN   NaN  ...   0.0   0.0   NaN   NaN   NaN   NaN   NaN
9    NaN   NaN   NaN   NaN  ...   0.0   0.0   NaN   NaN   NaN   NaN   NaN
10   NaN   NaN   NaN   NaN  ...   0.0   0.0   NaN   NaN   NaN   NaN   NaN
11   NaN   NaN   NaN   NaN  ...   0.0   0.0   NaN   NaN   NaN   NaN   NaN
12   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN
13   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN
14   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN
15   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN
16   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN
17   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN
18   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN
19   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN
20   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN
21   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN
22   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN
23   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN
24   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN
25   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN
26   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN
27   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN
28   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN
29   NaN   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN

    2029  2030  2031
0    NaN   NaN   NaN
1    NaN   NaN   NaN
2    NaN   NaN   NaN
3    NaN   NaN   NaN
4    NaN   NaN   NaN
5    NaN   NaN   NaN
6    NaN   NaN   NaN
7    NaN   NaN   NaN
8    NaN   NaN   NaN
9    NaN   NaN   NaN
10   NaN   NaN   NaN
11   NaN   NaN   NaN
12   NaN   NaN   NaN
13   NaN   NaN   NaN
14   NaN   NaN   NaN
15   NaN   NaN   NaN
16   NaN   NaN   NaN
17   NaN   NaN   NaN
18   NaN   NaN   NaN
19   NaN   NaN   NaN
20   NaN   NaN   NaN
21   NaN   NaN   NaN
22   NaN   NaN   NaN
23   NaN   NaN   NaN
24   NaN   NaN   NaN
25   NaN   NaN   NaN
26   NaN   NaN   NaN
27   NaN   NaN   NaN
28   NaN   NaN   NaN
29   NaN   NaN   NaN

[30 rows x 68 columns]

In [4]:
# Create a copy of the DataFrame
df = df_orig.copy()

print(df.head())

  Country Name Country Code Counterpart-Area Name Counterpart-Area Code  \
0  Afghanistan          AFG                 World                   WLD
1  Afghanistan          AFG                 World                   WLD
2  Afghanistan          AFG                 World                   WLD
3  Afghanistan          AFG                 World                   WLD
4  Afghanistan          AFG                 World                   WLD

                                         Series Name  Series Code  1970  1971  \
0  Average grace period on new external debt comm...  DT.GPA.DPPG   NaN   NaN
1  Average grace period on new external debt comm...  DT.GPA.OFFT   NaN   NaN
2  Average grace period on new external debt comm...  DT.GPA.PRVT   NaN   NaN
3  Average grant element on new external debt com...  DT.GRE.DPPG   NaN   NaN
4  Average grant element on new external debt com...  DT.GRE.OFFT   NaN   NaN

   1972  1973  ...  2022  2023  2024  2025  2026  2027  2028  2029  2030  2031
0   NaN   NaN  ...   0.0   0.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
1   NaN   NaN  ...   0.0   0.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
2   NaN   NaN  ...   0.0   0.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
3   NaN   NaN  ...   0.0   0.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
4   NaN   NaN  ...   0.0   0.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN

[5 rows x 68 columns]

# Exploring and Cleaning Data

In [5]:
#display data info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76921 entries, 0 to 76920
Data columns (total 68 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country Name           76918 non-null  object
 1   Country Code           76916 non-null  object
 2   Counterpart-Area Name  76916 non-null  object
 3   Counterpart-Area Code  76916 non-null  object
 4   Series Name            76916 non-null  object
 5   Series Code            76916 non-null  object
 6   1970                   32677 non-null  float64
 7   1971                   33639 non-null  float64
 8   1972                   34356 non-null  float64
 9   1973                   35126 non-null  float64
 10  1974                   35688 non-null  float64
 11  1975                   36470 non-null  float64
 12  1976                   36909 non-null  float64
 13  1977                   37872 non-null  float64
 14  1978                   38658 non-null  float64
 15  1979                   38925 non-null  float64
 16  1980                   39682 non-null  float64
 17  1981                   41647 non-null  float64
 18  1982                   41964 non-null  float64
 19  1983                   42275 non-null  float64
 20  1984                   42800 non-null  float64
 21  1985                   43212 non-null  float64
 22  1986                   43357 non-null  float64
 23  1987                   42957 non-null  float64
 24  1988                   42804 non-null  float64
 25  1989                   44091 non-null  float64
 26  1990                   44075 non-null  float64
 27  1991                   43919 non-null  float64
 28  1992                   45286 non-null  float64
 29  1993                   46473 non-null  float64
 30  1994                   47198 non-null  float64
 31  1995                   47480 non-null  float64
 32  1996                   48122 non-null  float64
 33  1997                   48096 non-null  float64
 34  1998                   48367 non-null  float64
 35  1999                   50114 non-null  float64
 36  2000                   49731 non-null  float64
 37  2001                   49710 non-null  float64
 38  2002                   49511 non-null  float64
 39  2003                   49242 non-null  float64
 40  2004                   49432 non-null  float64
 41  2005                   49349 non-null  float64
 42  2006                   49568 non-null  float64
 43  2007                   49831 non-null  float64
 44  2008                   49681 non-null  float64
 45  2009                   49937 non-null  float64
 46  2010                   49950 non-null  float64
 47  2011                   49232 non-null  float64
 48  2012                   49183 non-null  float64
 49  2013                   49546 non-null  float64
 50  2014                   50671 non-null  float64
 51  2015                   50583 non-null  float64
 52  2016                   50366 non-null  float64
 53  2017                   50498 non-null  float64
 54  2018                   50416 non-null  float64
 55  2019                   50280 non-null  float64
 56  2020                   50684 non-null  float64
 57  2021                   50503 non-null  float64
 58  2022                   50412 non-null  float64
 59  2023                   50389 non-null  float64
 60  2024                   12967 non-null  float64
 61  2025                   12765 non-null  float64
 62  2026                   12625 non-null  float64
 63  2027                   12472 non-null  float64
 64  2028                   12235 non-null  float64
 65  2029                   11999 non-null  float64
 66  2030                   11854 non-null  float64
 67  2031                   11579 non-null  float64
dtypes: float64(62), object(6)
memory usage: 39.9+ MB

In [6]:
# Print all the columns in the data
print(df.columns)

Index(['Country Name', 'Country Code', 'Counterpart-Area Name',
       'Counterpart-Area Code', 'Series Name', 'Series Code', '1970', '1971',
       '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980',
       '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989',
       '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998',
       '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
       '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025',
       '2026', '2027', '2028', '2029', '2030', '2031'],
      dtype='object')

In [7]:
# Dropping unneccesary columns
columns_to_drop = ['1970','1971','1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980',
       '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989',
       '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998',
       '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
       '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018','2025','2026', '2027', '2028', '2029', '2030', '2031']
df = df.drop(columns=columns_to_drop)

In [8]:
# Print all the columns in the data
print(df.columns)

Index(['Country Name', 'Country Code', 'Counterpart-Area Name',
       'Counterpart-Area Code', 'Series Name', 'Series Code', '2019', '2020',
       '2021', '2022', '2023', '2024'],
      dtype='object')

In [9]:
# Check for missing values
print(df.isnull().sum())

Country Name                 3
Country Code                 5
Counterpart-Area Name        5
Counterpart-Area Code        5
Series Name                  5
Series Code                  5
2019                     26641
2020                     26237
2021                     26418
2022                     26509
2023                     26532
2024                     63954
dtype: int64

In [10]:
# Print missing values for Country Name
print(df[df['Country Name'].isnull()])

      Country Name Country Code Counterpart-Area Name Counterpart-Area Code  \
76916          NaN          NaN                   NaN                   NaN
76917          NaN          NaN                   NaN                   NaN
76918          NaN          NaN                   NaN                   NaN

      Series Name Series Code  2019  2020  2021  2022  2023  2024
76916         NaN         NaN   NaN   NaN   NaN   NaN   NaN   NaN
76917         NaN         NaN   NaN   NaN   NaN   NaN   NaN   NaN
76918         NaN         NaN   NaN   NaN   NaN   NaN   NaN   NaN

In [11]:
df.head()

,Country Name,Country Code,Counterpart-Area Name,Counterpart-Area Code,Series Name,Series Code,2019,2020,2021,2022,2023,2024
0,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.DPPG,17.9041,0.0,0.0,0.0,0.0,NaN
1,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.OFFT,17.9041,0.0,0.0,0.0,0.0,NaN
2,Afghanistan,AFG,World,WLD,Average grace period on new external debt comm...,DT.GPA.PRVT,0.0000,0.0,0.0,0.0,0.0,NaN
3,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.DPPG,73.0790,0.0,0.0,0.0,0.0,NaN
4,Afghanistan,AFG,World,WLD,Average grant element on new external debt com...,DT.GRE.OFFT,73.0790,0.0,0.0,0.0,0.0,NaN

In [12]:
# Print all empty rows for country name
empty_country_name_rows = df[df['Country Name'].isnull()]
print(empty_country_name_rows)

      Country Name Country Code Counterpart-Area Name Counterpart-Area Code  \
76916          NaN          NaN                   NaN                   NaN
76917          NaN          NaN                   NaN                   NaN
76918          NaN          NaN                   NaN                   NaN

      Series Name Series Code  2019  2020  2021  2022  2023  2024
76916         NaN         NaN   NaN   NaN   NaN   NaN   NaN   NaN
76917         NaN         NaN   NaN   NaN   NaN   NaN   NaN   NaN
76918         NaN         NaN   NaN   NaN   NaN   NaN   NaN   NaN

In [13]:
# prompt: print cells where 2019 is empty

# Assuming 'df' is your DataFrame (as defined in the previous code)

# Print rows where the '2019' column is empty (NaN)
empty_2019_rows = df[df['2019'].isnull()]
empty_2019_rows

,Country Name,Country Code,Counterpart-Area Name,Counterpart-Area Code,Series Name,Series Code,2019,2020,2021,2022,2023,2024
12,Afghanistan,AFG,World,WLD,"CB, bilateral (AMT, current US$)",DT.AMT.BLAT.CB.CD,NaN,NaN,NaN,NaN,NaN,NaN
13,Afghanistan,AFG,World,WLD,"CB, bilateral (DIS, current US$)",DT.DIS.BLAT.CB.CD,NaN,NaN,NaN,NaN,NaN,NaN
14,Afghanistan,AFG,World,WLD,"CB, bilateral (DOD, current US$)",DT.DOD.BLAT.CB.CD,NaN,NaN,NaN,NaN,NaN,NaN
15,Afghanistan,AFG,World,WLD,"CB, bilateral (INT, current US$)",DT.INT.BLAT.CB.CD,NaN,NaN,NaN,NaN,NaN,NaN
16,Afghanistan,AFG,World,WLD,"CB, bilateral (NFL, current US$)",DT.NFL.BLAT.CB.CD,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
76916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76918,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76919,Data from database: International Debt Statistics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76920,Last Updated: 12/03/2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
# Drop rows with any NA values
df = df.dropna()

In [15]:
df.head()

,Country Name,Country Code,Counterpart-Area Name,Counterpart-Area Code,Series Name,Series Code,2019,2020,2021,2022,2023,2024
98,Afghanistan,AFG,World,WLD,"Debt service on external debt, general governm...",DT.TDS.DEGG.CD,32780041.6,28700402.1,19234000.0,12017000.0,13220000.0,129672654.3
99,Afghanistan,AFG,World,WLD,"Debt service on external debt, long-term (TDS,...",DT.TDS.DLXF.CD,39807041.6,34557402.1,19234000.0,12017000.0,13220000.0,135241654.3
103,Afghanistan,AFG,World,WLD,"Debt service on external debt, public and publ...",DT.TDS.DPPG.CD,32780041.6,28700402.1,19234000.0,12017000.0,13220000.0,129672654.3
104,Afghanistan,AFG,World,WLD,"Debt service on external debt, public sector (...",DT.TDS.DEPS.CD,32780041.6,28700402.1,19234000.0,12017000.0,13220000.0,129672654.3
105,Afghanistan,AFG,World,WLD,"Debt service on external debt, total (TDS, cur...",DT.TDS.DECT.CD,55575662.9,45904311.7,25997304.5,26580940.3,43570332.3,141882918.7

In [16]:
# drop column Series Code
df = df.drop(columns=['Series Code'])

In [19]:
# Summary statistics for numerical columns
print(df.describe())

               2019          2020          2021          2022          2023  \
count  1.195300e+04  1.195300e+04  1.195300e+04  1.195300e+04  1.195300e+04
mean   6.036034e+09  5.874952e+09  6.309123e+09  6.373652e+09  6.650388e+09
std    4.134574e+10  3.999935e+10  4.242832e+10  4.342215e+10  4.588618e+10
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
25%    1.494733e+07  1.496740e+07  1.421325e+07  1.599300e+07  1.913583e+07
50%    1.250130e+08  1.232640e+08  1.234177e+08  1.329474e+08  1.530830e+08
75%    1.095798e+09  1.014386e+09  1.059367e+09  1.002784e+09  1.207389e+09
max    1.134440e+12  1.139830e+12  1.156220e+12  1.240030e+12  1.356610e+12

               2024
count  1.195300e+04
mean   6.804935e+09
std    3.833338e+10
min    0.000000e+00
25%    2.619415e+07
50%    2.113926e+08
75%    1.555001e+09
max    1.162970e+12

In [20]:
# Value counts for categorical columns (if any)
# Example: if 'Country Name' is categorical
print(df['Country Name'].value_counts())

Country Name
Lower middle income                            143
Middle income                                  143
Low & middle income                            143
Upper middle income                            142
East Asia & Pacific (excluding high income)    140
                                              ...
Tonga                                           44
Yemen, Rep.                                     40
Afghanistan                                     40
Timor-Leste                                     39
Syrian Arab Republic                            16
Name: count, Length: 134, dtype: int64

In [21]:
brazil_rows = df[df['Country Name'] == 'Brazil']
print(brazil_rows)

     Country Name Country Code Counterpart-Area Name Counterpart-Area Code  \
8708       Brazil          BRA                 World                   WLD
8709       Brazil          BRA                 World                   WLD
8710       Brazil          BRA                 World                   WLD
8711       Brazil          BRA                 World                   WLD
8712       Brazil          BRA                 World                   WLD
...           ...          ...                   ...                   ...
9158       Brazil          BRA                 World                   WLD
9161       Brazil          BRA                 World                   WLD
9162       Brazil          BRA                 World                   WLD
9165       Brazil          BRA                 World                   WLD
9168       Brazil          BRA                 World                   WLD

                                            Series Name          2019  \
8708  Debt service on external debt, general governm...  8.224003e+09
8709  Debt service on external debt, long-term (TDS,...  1.491650e+11
8710  Debt service on external debt, other public se...  3.337312e+10
8711  Debt service on external debt, private guarant...  2.928676e+08
8712  Debt service on external debt, private nonguar...  1.072750e+11
...                                                 ...           ...
9158     PS, other private creditors (INT, current US$)  5.590675e+09
9161     PS, other private creditors (TDS, current US$)  1.870412e+10
9162           PS, private creditors (AMT, current US$)  2.205769e+10
9165           PS, private creditors (INT, current US$)  9.701341e+09
9168           PS, private creditors (TDS, current US$)  3.175904e+10

              2020          2021          2022          2023          2024
8708  6.457454e+09  9.819054e+09  6.631095e+09  7.206782e+09  1.311826e+10
8709  1.288880e+11  1.610020e+11  1.240030e+11  2.209540e+11  9.533385e+10
8710  2.423157e+10  1.883325e+10  2.393138e+10  2.304108e+10  1.281211e+10
8711  2.444949e+08  2.561237e+08  3.348180e+08  1.260580e+09  4.287994e+08
8712  9.795466e+10  1.320940e+11  9.310552e+10  1.894450e+11  6.897468e+10
...            ...           ...           ...           ...           ...
9158  3.182051e+09  4.176459e+09  3.470387e+09  3.952218e+09  3.949830e+09
9161  1.711448e+10  1.380889e+10  1.761481e+10  1.637503e+10  4.818068e+09
9162  2.039052e+10  1.642060e+10  1.873986e+10  1.717724e+10  1.202087e+10
9165  6.791785e+09  7.707835e+09  6.977595e+09  7.274877e+09  7.910300e+09
9168  2.718230e+10  2.412844e+10  2.571746e+10  2.445211e+10  1.993117e+10

[137 rows x 11 columns]

In [22]:
# List all unique rows in Series Name column
unique_countries = df['Series Name'].unique()
unique_countries

array(['Debt service on external debt, general government sector (PPG) (TDS, current US$)',
       'Debt service on external debt, long-term (TDS, current US$)',
       'Debt service on external debt, public and publicly guaranteed (PPG) (TDS, current US$)',
       'Debt service on external debt, public sector (PPG) (TDS, current US$)',
       'Debt service on external debt, total (TDS, current US$)',
       'Disbursements on external debt, long-term (DIS, current US$)',
       'Disbursements on external debt, public and publicly guaranteed (PPG) (DIS, current US$)',
       'GG, multilateral (AMT, current US$)',
       'GG, multilateral (INT, current US$)',
       'GG, multilateral (TDS, current US$)',
       'GG, official creditors (AMT, current US$)',
       'GG, official creditors (INT, current US$)',
       'GG, official creditors (TDS, current US$)',
       'IMF credit and SDR allocations, charges (INT, current US$)',
       'IMF credit, charges (INT, current US$)',
       'IMF repurchases (AMT, current US$)',
       'IMF repurchases and charges (TDS, current US$)',
       'Interest payments on external debt, general government sector (PPG) (INT, current US$)',
       'Interest payments on external debt, long-term (INT, current US$)',
       'Interest payments on external debt, public and publicly guaranteed (PPG) (INT, current US$)',
       'Interest payments on external debt, public sector (PPG) (INT, current US$)',
       'Multilateral debt service (TDS, current US$)',
       'PPG, bilateral (DIS, current US$)',
       'PPG, multilateral (AMT, current US$)',
       'PPG, multilateral (DIS, current US$)',
       'PPG, multilateral (INT, current US$)',
       'PPG, official creditors (AMT, current US$)',
       'PPG, official creditors (DIS, current US$)',
       'PPG, official creditors (INT, current US$)',
       'Principal repayments on external debt, general government sector (PPG) (AMT, current US$)',
       'Principal repayments on external debt, long-term (AMT, current US$)',
       'Principal repayments on external debt, public and publicly guaranteed (PPG) (AMT, current US$)',
       'PS, multilateral (AMT, current US$)',
       'PS, multilateral (INT, current US$)',
       'PS, multilateral (TDS, current US$)',
       'PS, multilateral concessional (AMT, current US$)',
       'PS, multilateral concessional (INT, current US$)',
       'PS, official creditors (AMT, current US$)',
       'PS, official creditors (INT, current US$)',
       'PS, official creditors (TDS, current US$)',
       'Debt service on external debt, other public sector (PPG) (TDS, current US$)',
       'Debt service on external debt, private nonguaranteed (PNG) (TDS, current US$)',
       'GG, bilateral (AMT, current US$)',
       'GG, bilateral (INT, current US$)',
       'GG, bilateral (TDS, current US$)', 'GG, bonds (INT, current US$)',
       'GG, bonds (TDS, current US$)',
       'GG, commercial banks (AMT, current US$)',
       'GG, commercial banks (INT, current US$)',
       'GG, commercial banks (TDS, current US$)',
       'GG, other private creditors (AMT, current US$)',
       'GG, other private creditors (INT, current US$)',
       'GG, other private creditors (TDS, current US$)',
       'GG, private creditors (AMT, current US$)',
       'GG, private creditors (INT, current US$)',
       'GG, private creditors (TDS, current US$)',
       'Interest payments on external debt, other public sector (PPG) (INT, current US$)',
       'Interest payments on external debt, private nonguaranteed (PNG) (INT, current US$)',
       'OPS, bilateral (AMT, current US$)',
       'OPS, bilateral (INT, current US$)',
       'OPS, bilateral (TDS, current US$)',
       'OPS, commercial banks (AMT, current US$)',
       'OPS, commercial banks (INT, current US$)',
       'OPS, commercial banks (TDS, current US$)',
       'OPS, multilateral (AMT, current US$)',
       'OPS, multilateral (INT, current US$)',
       'OPS, multilateral (TDS, current US$)',
       'OPS, official creditors (AMT, current US$)',
       'OPS, official creditors (INT, current US$)',
       'OPS, official creditors (TDS, current US$)',
       'OPS, private creditors (AMT, current US$)',
       'OPS, private creditors (INT, current US$)',
       'OPS, private creditors (TDS, current US$)',
       'PNG, bonds (AMT, current US$)', 'PNG, bonds (INT, current US$)',
       'PNG, bonds (TDS, current US$)',
       'PNG, commercial banks and other creditors (AMT, current US$)',
       'PNG, commercial banks and other creditors (INT, current US$)',
       'PNG, commercial banks and other creditors (TDS, current US$)',
       'PPG, bilateral (AMT, current US$)',
       'PPG, bilateral (INT, current US$)',
       'PPG, bilateral (TDS, current US$)',
       'PPG, bilateral concessional (AMT, current US$)',
       'PPG, bilateral concessional (INT, current US$)',
       'PPG, bilateral concessional (TDS, current US$)',
       'PPG, bonds (INT, current US$)', 'PPG, bonds (TDS, current US$)',
       'PPG, commercial banks (AMT, current US$)',
       'PPG, commercial banks (DIS, current US$)',
       'PPG, commercial banks (INT, current US$)',
       'PPG, commercial banks (TDS, current US$)',
       'PPG, other private creditors (AMT, current US$)',
       'PPG, other private creditors (INT, current US$)',
       'PPG, private creditors (AMT, current US$)',
       'PPG, private creditors (DIS, current US$)',
       'PPG, private creditors (INT, current US$)',
       'PPG, private creditors (TDS, current US$)',
       'Principal repayments on external debt, other public sector (PPG) (AMT, current US$)',
       'Principal repayments on external debt, private nonguaranteed (PNG) (AMT, current US$)',
       'PS, bilateral (AMT, current US$)',
       'PS, bilateral (INT, current US$)',
       'PS, bilateral (TDS, current US$)', 'PS, bonds (INT, current US$)',
       'PS, bonds (TDS, current US$)',
       'PS, commercial banks (AMT, current US$)',
       'PS, commercial banks (INT, current US$)',
       'PS, commercial banks (TDS, current US$)',
       'PS, other private creditors (AMT, current US$)',
       'PS, other private creditors (INT, current US$)',
       'PS, other private creditors (TDS, current US$)',
       'PS, private creditors (AMT, current US$)',
       'PS, private creditors (INT, current US$)',
       'PS, private creditors (TDS, current US$)',
       'GG, bonds (AMT, current US$)',
       'OPS, other private creditors (AMT, current US$)',
       'OPS, other private creditors (TDS, current US$)',
       'PPG, bonds (AMT, current US$)',
       'PPG, other private creditors (DIS, current US$)',
       'PS, bonds (AMT, current US$)', 'OPS, bonds (INT, current US$)',
       'OPS, bonds (TDS, current US$)',
       'OPS, multilateral concessional (AMT, current US$)',
       'OPS, multilateral concessional (INT, current US$)',
       'OPS, multilateral concessional (TDS, current US$)',
       'Debt service on external debt, private guaranteed by public sector (PPG) (TDS, current US$)',
       'Interest payments on external debt, private guaranteed by public sector (PPG) (INT, current US$)',
       'OPS, bonds (AMT, current US$)',
       'OPS, other private creditors (INT, current US$)',
       'Principal repayments on external debt, private guaranteed by public sector (PPG) (AMT, current US$)',
       'PRVG, commercial banks (AMT, current US$)',
       'PRVG, commercial banks (INT, current US$)',
       'PRVG, commercial banks (TDS, current US$)',
       'PRVG, multilateral (AMT, current US$)',
       'PRVG, multilateral (INT, current US$)',
       'PRVG, multilateral (TDS, current US$)',
       'PRVG, official creditors (AMT, current US$)',
       'PRVG, official creditors (INT, current US$)',
       'PRVG, official creditors (TDS, current US$)',
       'PRVG, private creditors (AMT, current US$)',
       'PRVG, private creditors (INT, current US$)',
       'PRVG, private creditors (TDS, current US$)',
       'PRVG, bilateral (AMT, current US$)',
       'PRVG, bilateral (INT, current US$)',
       'PRVG, bilateral (TDS, current US$)'], dtype=object)

In [ ]:
# Keep only rows that have GG, official creditors (AMT, current US$)', 'Debt service on external debt, total (TDS, current US$)', 'Short-term external debt (DOD, current US$) under Series Name

# Keep only rows that have specific values in 'Series Name' column
series_names_to_keep = ['GG, official creditors (AMT, current US$)',
                        'Debt service on external debt, total (TDS, current US$)',
                        'Short-term external debt (DOD, current US$)']
df = df[df['Series Name'].isin(series_names_to_keep)]
print(df.head(20))